services:
  - type: web
    name: rag-system
    env: python
    plan: free
    buildCommand: "git submodule update --init && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    rootDir: "rag_project"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
